module UsersHelper

  def job_list
    ["Airlines/Aviation",
    "Alternative Medicine",
    "Animation",
    "Apparel & Fashion",
    "Architecture & Planning",
    "Arts and Crafts",
    "Automotive",
    "Aviation & Aerospace",
    "Banking",
    "Broadcast Media",
    "Building Materials",
    "Civil Engineering",
    "Computer & Network Security",
    "Computer Games",
    "Construction",
    "Defense & Space",
    "Education Management",
    "Entertainment",
    "Environmental Services",
    "Farming",
    "Financial Services",
    "Fine Art",
    "Food & Beverages",
    "Gambling & Casinos",
    "Government Administration",
    "Graphic Design",
    "Health, Wellness and Fitness",
    "Higher Education",
    "Hospital & Health Care",
    "Hospitality",
    "Human Resources",
    "Information Services",
    "Information Technology",
    "Insurance",
    "International Affairs",
    "Law Enforcement",
    "Law Practice",
    "Legal Services",
    "Legislative Office",
    "Leisure, Travel & Tourism",
    "Libraries",
    "Marketing and Advertising",
    "Media Production",
    "Mental Health Care",
    "Military",
    "Music",
    "Newspapers",
    "Non-Profit Organization Management",
    "Package/Freight Delivery",
    "Performing Arts",
    "Pharmaceuticals",
    "Philanthropy",
    "Photography",
    "Political Organization",
    "Primary/Secondary Education",
    "Printing",
    "Public Policy",
    "Public Relations and Communications",
    "Public Safety",
    "Publishing",
    "Real Estate",
    "Restaurants",
    "Retail",
    "Sports",
    "Staffing and Recruiting",
    "Transportation/Trucking/Railroad",
    "Utilities",
    "Veterinary",
    "Warehousing",
    "Wine and Spirits",
    "Writing and Editing"]
  end

end
